# Generated by Django 3.1.1 on 2021-03-30 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='docpics')),
                ('gender', models.CharField(max_length=200)),
                ('specialist', models.TextField()),
                ('degree', models.TextField()),
                ('contno', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('fee', models.IntegerField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
