# Generated by Django 3.1.1 on 2021-03-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctorprofile_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='licence',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='photo',
            field=models.URLField(),
        ),
    ]
