# Generated by Django 3.1.1 on 2021-03-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210330_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='photo',
            field=models.FileField(upload_to='docpics'),
        ),
    ]
