# Generated by Django 3.1.1 on 2021-03-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210331_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='licence',
            field=models.FileField(upload_to='docpics'),
        ),
    ]
