# Generated by Django 3.1.1 on 2021-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210331_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='Upload_Profile',
            field=models.BooleanField(default=True),
        ),
    ]
