# Generated by Django 3.1.1 on 2021-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctorprofile_upload_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
