# Generated by Django 3.1.1 on 2021-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210331_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='Upload_Profile',
            field=models.BooleanField(default=False),
        ),
    ]
