# Generated by Django 3.1.1 on 2021-04-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_doctorprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='slug',
        ),
    ]
