# Generated by Django 3.1.1 on 2021-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_patientdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='pid',
            field=models.IntegerField(default=False),
        ),
    ]
