# Generated by Django 3.1.1 on 2021-04-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210403_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='nowdatetime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
