# Generated by Django 3.1.1 on 2021-05-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210410_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetails',
            options={'ordering': ('-date', '-time')},
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='give_a_message',
            field=models.TextField(null=True),
        ),
    ]
