# Generated by Django 3.1.1 on 2021-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210502_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='give_a_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
