# Generated by Django 3.1.1 on 2021-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210502_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='purpose_of_meeting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
