# Generated by Django 3.1.1 on 2021-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_patientdetails_purpose_of_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='purpose_of_meeting',
            field=models.TextField(),
        ),
    ]
