# Generated by Django 3.1.1 on 2021-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210518_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='payment',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
