# Generated by Django 3.1.1 on 2021-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_patientdetails_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='payment',
            field=models.CharField(max_length=1),
        ),
    ]
