# Generated by Django 3.1.1 on 2021-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210518_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='Clinic_or_Hospital_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
