# Generated by Django 3.1.1 on 2021-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_doctorprofile_clinic_or_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='Clinic_or_Hospital_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
